[20240513 17:45:49 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:45:51 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:45:51 save_data.py:20 INFO]: Linking DB error
[20240513 17:45:54 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:45:56 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:45:56 save_data.py:20 INFO]: Linking DB error
[20240513 17:45:58 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:46:00 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:46:00 save_data.py:20 INFO]: Linking DB error
[20240513 17:46:03 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:46:05 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:46:05 save_data.py:20 INFO]: Linking DB error
[20240513 17:46:07 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:46:10 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:46:10 save_data.py:20 INFO]: Linking DB error
[20240513 17:46:12 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:46:14 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:46:14 save_data.py:20 INFO]: Linking DB error
[20240513 17:46:16 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:46:19 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:46:19 save_data.py:20 INFO]: Linking DB error
[20240513 17:46:21 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:46:23 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:46:23 save_data.py:20 INFO]: Linking DB error
[20240513 17:46:25 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:46:28 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:46:28 save_data.py:20 INFO]: Linking DB error
[20240513 17:48:58 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:49:01 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:49:01 save_data.py:20 INFO]: Linking DB error
[20240513 17:49:03 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:49:05 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:49:05 save_data.py:20 INFO]: Linking DB error
[20240513 17:49:08 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:49:10 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:49:10 save_data.py:20 INFO]: Linking DB error
[20240513 17:49:12 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:49:14 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:49:14 save_data.py:20 INFO]: Linking DB error
[20240513 17:49:17 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:49:19 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:49:19 save_data.py:20 INFO]: Linking DB error
[20240513 17:49:21 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:49:24 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:49:24 save_data.py:20 INFO]: Linking DB error
[20240513 17:49:26 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:49:28 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:49:28 save_data.py:20 INFO]: Linking DB error
[20240513 17:49:30 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:49:33 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:49:33 save_data.py:20 INFO]: Linking DB error
[20240513 17:49:35 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:49:37 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:49:37 save_data.py:20 INFO]: Linking DB error
[20240513 17:58:39 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:58:42 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:58:42 save_data.py:20 INFO]: Linking DB error
[20240513 17:58:44 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:58:46 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:58:46 save_data.py:20 INFO]: Linking DB error
[20240513 17:58:48 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:58:51 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:58:51 save_data.py:20 INFO]: Linking DB error
[20240513 17:58:53 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:58:55 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:58:55 save_data.py:20 INFO]: Linking DB error
[20240513 17:58:58 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:00 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:00 save_data.py:20 INFO]: Linking DB error
[20240513 17:59:02 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:04 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:04 save_data.py:20 INFO]: Linking DB error
[20240513 17:59:07 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:09 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:09 save_data.py:20 INFO]: Linking DB error
[20240513 17:59:11 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:14 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:14 save_data.py:20 INFO]: Linking DB error
[20240513 17:59:16 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:18 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:18 save_data.py:20 INFO]: Linking DB error
[20240513 17:59:20 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:23 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:23 save_data.py:20 INFO]: Linking DB error
[20240513 17:59:25 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:27 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:27 save_data.py:20 INFO]: Linking DB error
[20240513 17:59:30 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:32 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:32 save_data.py:20 INFO]: Linking DB error
[20240513 17:59:34 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:36 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:36 save_data.py:20 INFO]: Linking DB error
[20240513 17:59:39 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:41 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:41 save_data.py:20 INFO]: Linking DB error
[20240513 17:59:43 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:46 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:46 save_data.py:20 INFO]: Linking DB error
[20240513 17:59:48 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:50 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:50 save_data.py:20 INFO]: Linking DB error
[20240513 17:59:52 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:55 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:55 save_data.py:20 INFO]: Linking DB error
[20240513 17:59:57 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:59 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 17:59:59 save_data.py:20 INFO]: Linking DB error
[20240513 18:00:02 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:00:04 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:00:04 save_data.py:20 INFO]: Linking DB error
[20240513 18:00:06 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:00:08 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:00:08 save_data.py:20 INFO]: Linking DB error
[20240513 18:00:11 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:00:13 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:00:13 save_data.py:20 INFO]: Linking DB error
[20240513 18:00:15 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:00:18 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:00:18 save_data.py:20 INFO]: Linking DB error
[20240513 18:00:20 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:00:22 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:00:22 save_data.py:20 INFO]: Linking DB error
[20240513 18:00:24 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:00:27 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:00:27 save_data.py:20 INFO]: Linking DB error
[20240513 18:00:29 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:00:31 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:00:31 save_data.py:20 INFO]: Linking DB error
[20240513 18:00:34 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:00:36 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:00:36 save_data.py:20 INFO]: Linking DB error
[20240513 18:00:38 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:00:40 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:00:40 save_data.py:20 INFO]: Linking DB error
[20240513 18:00:43 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:00:45 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:00:45 save_data.py:20 INFO]: Linking DB error
[20240513 18:00:47 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:00:50 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:00:50 save_data.py:20 INFO]: Linking DB error
[20240513 18:00:52 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:00:54 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:00:54 save_data.py:20 INFO]: Linking DB error
[20240513 18:00:56 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:00:59 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:00:59 save_data.py:20 INFO]: Linking DB error
[20240513 18:01:01 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:01:03 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:01:03 save_data.py:20 INFO]: Linking DB error
[20240513 18:01:06 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:01:08 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:01:08 save_data.py:20 INFO]: Linking DB error
[20240513 18:01:10 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:01:12 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:01:12 save_data.py:20 INFO]: Linking DB error
[20240513 18:01:15 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:01:17 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:01:17 save_data.py:20 INFO]: Linking DB error
[20240513 18:01:19 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:01:22 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:01:22 save_data.py:20 INFO]: Linking DB error
[20240513 18:01:22 base_events.py:40 ERROR]: Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 遠端主機已強制關閉一個現存的連線。
[20240513 18:01:22 base_events.py:40 ERROR]: Exception in callback BaseProactorEventLoop._start_serving.<locals>.loop(<_OverlappedF...0.1', 55365))>) at C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py:818
handle: <Handle BaseProactorEventLoop._start_serving.<locals>.loop(<_OverlappedF...0.1', 55365))>) at C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py:818>
Traceback (most recent call last):
  File "C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 832, in loop
    self._make_socket_transport(
  File "C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 639, in _make_socket_transport
    return _ProactorSocketTransport(self, sock, protocol, waiter,
  File "C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 605, in __init__
    super().__init__(loop, sock, protocol, waiter, extra, server)
  File "C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 185, in __init__
    super().__init__(loop, sock, protocol, waiter, extra, server)
  File "C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 330, in __init__
    super().__init__(*args, **kw)
  File "C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 65, in __init__
    self._server._attach()
  File "C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 297, in _attach
    assert self._sockets is not None
AssertionError
[20240513 18:01:24 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:01:26 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:01:26 save_data.py:20 INFO]: Linking DB error
[20240513 18:01:28 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:01:31 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:01:31 save_data.py:20 INFO]: Linking DB error
[20240513 18:01:33 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:01:35 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:01:35 save_data.py:20 INFO]: Linking DB error
[20240513 18:01:38 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:01:40 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:01:40 save_data.py:20 INFO]: Linking DB error
[20240513 18:01:42 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:01:44 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:01:44 save_data.py:20 INFO]: Linking DB error
[20240513 18:01:47 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:01:49 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:01:49 save_data.py:20 INFO]: Linking DB error
[20240513 18:09:35 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:09:37 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:09:37 save_data.py:20 INFO]: Linking DB error
[20240513 18:09:40 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:09:42 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:09:42 save_data.py:20 INFO]: Linking DB error
[20240513 18:09:44 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:09:46 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:09:46 save_data.py:20 INFO]: Linking DB error
[20240513 18:09:49 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:09:51 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:09:51 save_data.py:20 INFO]: Linking DB error
[20240513 18:09:53 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:09:56 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:09:56 save_data.py:20 INFO]: Linking DB error
[20240513 18:09:58 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:10:00 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:10:00 save_data.py:20 INFO]: Linking DB error
[20240513 18:10:02 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:10:05 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:10:05 save_data.py:20 INFO]: Linking DB error
[20240513 18:10:07 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:10:09 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:10:09 save_data.py:20 INFO]: Linking DB error
[20240513 18:10:12 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:10:14 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:10:14 save_data.py:20 INFO]: Linking DB error
[20240513 18:11:44 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:11:47 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:11:47 save_data.py:20 INFO]: Linking DB error
[20240513 18:11:49 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:11:51 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:11:51 save_data.py:20 INFO]: Linking DB error
[20240513 18:11:53 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:11:56 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:11:56 save_data.py:20 INFO]: Linking DB error
[20240513 18:11:58 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:12:00 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:12:00 save_data.py:20 INFO]: Linking DB error
[20240513 18:12:03 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:12:05 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:12:05 save_data.py:20 INFO]: Linking DB error
[20240513 18:12:07 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:12:09 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:12:09 save_data.py:20 INFO]: Linking DB error
[20240513 18:12:12 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:12:14 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:12:14 save_data.py:20 INFO]: Linking DB error
[20240513 18:12:16 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:12:19 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:12:19 save_data.py:20 INFO]: Linking DB error
[20240513 18:12:21 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:12:23 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:12:23 save_data.py:20 INFO]: Linking DB error
[20240513 18:12:25 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:12:28 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:12:28 save_data.py:20 INFO]: Linking DB error
[20240513 18:12:30 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:12:32 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:12:32 save_data.py:20 INFO]: Linking DB error
[20240513 18:12:35 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:12:37 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:12:37 save_data.py:20 INFO]: Linking DB error
[20240513 18:12:39 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:12:41 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:12:41 save_data.py:20 INFO]: Linking DB error
[20240513 18:12:44 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:12:46 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:12:46 save_data.py:20 INFO]: Linking DB error
[20240513 18:12:48 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:12:51 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:12:51 save_data.py:20 INFO]: Linking DB error
[20240513 18:12:53 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:12:55 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:12:55 save_data.py:20 INFO]: Linking DB error
[20240513 18:12:57 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:00 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:00 save_data.py:20 INFO]: Linking DB error
[20240513 18:13:02 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:04 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:04 save_data.py:20 INFO]: Linking DB error
[20240513 18:13:07 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:09 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:09 save_data.py:20 INFO]: Linking DB error
[20240513 18:13:11 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:13 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:13 save_data.py:20 INFO]: Linking DB error
[20240513 18:13:16 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:18 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:18 save_data.py:20 INFO]: Linking DB error
[20240513 18:13:20 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:22 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:22 save_data.py:20 INFO]: Linking DB error
[20240513 18:13:25 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:27 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:27 save_data.py:20 INFO]: Linking DB error
[20240513 18:13:29 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:32 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:32 save_data.py:20 INFO]: Linking DB error
[20240513 18:13:34 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:36 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:36 save_data.py:20 INFO]: Linking DB error
[20240513 18:13:38 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:41 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:41 save_data.py:20 INFO]: Linking DB error
[20240513 18:13:43 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:45 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:45 save_data.py:20 INFO]: Linking DB error
[20240513 18:13:48 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:50 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:50 save_data.py:20 INFO]: Linking DB error
[20240513 18:13:52 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:54 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:54 save_data.py:20 INFO]: Linking DB error
[20240513 18:13:57 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:59 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:13:59 save_data.py:20 INFO]: Linking DB error
[20240513 18:14:01 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:14:03 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:14:03 save_data.py:20 INFO]: Linking DB error
[20240513 18:14:06 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:14:08 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:14:08 save_data.py:20 INFO]: Linking DB error
[20240513 18:14:10 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:14:13 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:14:13 save_data.py:20 INFO]: Linking DB error
[20240513 18:14:15 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:14:17 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:14:17 save_data.py:20 INFO]: Linking DB error
[20240513 18:14:19 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:14:22 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:14:22 save_data.py:20 INFO]: Linking DB error
[20240513 18:14:24 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:14:26 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:14:26 save_data.py:20 INFO]: Linking DB error
[20240513 18:14:26 base_events.py:40 ERROR]: Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 遠端主機已強制關閉一個現存的連線。
[20240513 18:14:58 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:15:00 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:15:00 save_data.py:20 INFO]: Linking DB error
[20240513 18:15:03 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:15:05 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:15:05 save_data.py:20 INFO]: Linking DB error
[20240513 18:15:07 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:15:09 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:15:09 save_data.py:20 INFO]: Linking DB error
[20240513 18:15:12 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:15:14 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:15:14 save_data.py:20 INFO]: Linking DB error
[20240513 18:15:16 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:15:19 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:15:19 save_data.py:20 INFO]: Linking DB error
[20240513 18:15:21 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:15:23 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:15:23 save_data.py:20 INFO]: Linking DB error
[20240513 18:15:25 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:15:28 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:15:28 save_data.py:20 INFO]: Linking DB error
[20240513 18:15:30 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:15:32 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:15:32 save_data.py:20 INFO]: Linking DB error
[20240513 18:15:35 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:15:37 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:15:37 save_data.py:20 INFO]: Linking DB error
[20240513 18:15:57 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:16:00 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:16:00 save_data.py:20 INFO]: Linking DB error
[20240513 18:16:02 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:16:04 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:16:04 save_data.py:20 INFO]: Linking DB error
[20240513 18:16:06 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:16:09 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:16:09 save_data.py:20 INFO]: Linking DB error
[20240513 18:16:11 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:16:13 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:16:13 save_data.py:20 INFO]: Linking DB error
[20240513 18:16:16 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:16:18 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:16:18 save_data.py:20 INFO]: Linking DB error
[20240513 18:16:20 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:16:22 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:16:22 save_data.py:20 INFO]: Linking DB error
[20240513 18:16:25 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:16:27 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:16:27 save_data.py:20 INFO]: Linking DB error
[20240513 18:16:29 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:16:32 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:16:32 save_data.py:20 INFO]: Linking DB error
[20240513 18:16:34 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:16:36 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:16:36 save_data.py:20 INFO]: Linking DB error
[20240513 18:17:37 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:17:39 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:17:39 save_data.py:20 INFO]: Linking DB error
[20240513 18:17:41 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:17:44 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:17:44 save_data.py:20 INFO]: Linking DB error
[20240513 18:17:46 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:17:48 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:17:48 save_data.py:20 INFO]: Linking DB error
[20240513 18:17:51 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:17:53 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:17:53 save_data.py:20 INFO]: Linking DB error
[20240513 18:17:55 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:17:57 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:17:57 save_data.py:20 INFO]: Linking DB error
[20240513 18:18:00 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:18:02 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:18:02 save_data.py:20 INFO]: Linking DB error
[20240513 18:18:04 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:18:07 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:18:07 save_data.py:20 INFO]: Linking DB error
[20240513 18:18:09 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:18:11 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:18:11 save_data.py:20 INFO]: Linking DB error
[20240513 18:18:13 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:18:16 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:18:16 save_data.py:20 INFO]: Linking DB error
[20240513 18:19:07 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:19:09 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:19:09 save_data.py:20 INFO]: Linking DB error
[20240513 18:19:11 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:19:14 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:19:14 save_data.py:20 INFO]: Linking DB error
[20240513 18:19:16 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:19:18 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:19:18 save_data.py:20 INFO]: Linking DB error
[20240513 18:19:20 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:19:23 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:19:23 save_data.py:20 INFO]: Linking DB error
[20240513 18:19:25 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:19:27 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:19:27 save_data.py:20 INFO]: Linking DB error
[20240513 18:19:30 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:19:32 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:19:32 save_data.py:20 INFO]: Linking DB error
[20240513 18:19:34 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:19:36 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:19:36 save_data.py:20 INFO]: Linking DB error
[20240513 18:19:39 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:19:41 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:19:41 save_data.py:20 INFO]: Linking DB error
[20240513 18:19:43 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:19:46 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:19:46 save_data.py:20 INFO]: Linking DB error
[20240513 18:25:21 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:25:23 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:25:23 save_data.py:20 INFO]: Linking DB error
[20240513 18:25:25 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:25:28 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:25:28 save_data.py:20 INFO]: Linking DB error
[20240513 18:25:30 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:25:32 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:25:32 save_data.py:20 INFO]: Linking DB error
[20240513 18:25:34 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:25:37 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:25:37 save_data.py:20 INFO]: Linking DB error
[20240513 18:25:39 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:25:41 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:25:41 save_data.py:20 INFO]: Linking DB error
[20240513 18:25:44 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:25:46 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:25:46 save_data.py:20 INFO]: Linking DB error
[20240513 18:25:48 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:25:50 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:25:50 save_data.py:20 INFO]: Linking DB error
[20240513 18:25:53 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:25:55 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:25:55 save_data.py:20 INFO]: Linking DB error
[20240513 18:25:57 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:26:00 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:26:00 save_data.py:20 INFO]: Linking DB error
[20240513 18:27:39 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:27:41 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:27:41 save_data.py:20 INFO]: Linking DB error
[20240513 18:27:43 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:27:46 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:27:46 save_data.py:20 INFO]: Linking DB error
[20240513 18:27:48 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:27:50 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:27:50 save_data.py:20 INFO]: Linking DB error
[20240513 18:27:53 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:27:55 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:27:55 save_data.py:20 INFO]: Linking DB error
[20240513 18:27:57 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:27:59 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:27:59 save_data.py:20 INFO]: Linking DB error
[20240513 18:28:02 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:28:04 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:28:04 save_data.py:20 INFO]: Linking DB error
[20240513 18:28:06 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:28:09 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:28:09 save_data.py:20 INFO]: Linking DB error
[20240513 18:28:11 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:28:13 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:28:13 save_data.py:20 INFO]: Linking DB error
[20240513 18:28:15 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:28:18 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:28:18 save_data.py:20 INFO]: Linking DB error
[20240513 18:37:03 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:37:05 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:37:05 save_data.py:20 INFO]: Linking DB error
[20240513 18:37:08 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:37:10 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:37:10 save_data.py:20 INFO]: Linking DB error
[20240513 18:37:12 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:37:14 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:37:14 save_data.py:20 INFO]: Linking DB error
[20240513 18:37:17 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:37:19 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:37:19 save_data.py:20 INFO]: Linking DB error
[20240513 18:37:21 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:37:24 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:37:24 save_data.py:20 INFO]: Linking DB error
[20240513 18:37:26 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:37:28 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:37:28 save_data.py:20 INFO]: Linking DB error
[20240513 18:37:30 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:37:33 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:37:33 save_data.py:20 INFO]: Linking DB error
[20240513 18:37:35 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:37:37 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:37:37 save_data.py:20 INFO]: Linking DB error
[20240513 18:37:40 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:37:42 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:37:42 save_data.py:20 INFO]: Linking DB error
[20240513 18:38:39 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:38:41 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:38:41 save_data.py:20 INFO]: Linking DB error
[20240513 18:38:43 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:38:46 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:38:46 save_data.py:20 INFO]: Linking DB error
[20240513 18:38:48 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:38:50 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:38:50 save_data.py:20 INFO]: Linking DB error
[20240513 18:38:53 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:38:55 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:38:55 save_data.py:20 INFO]: Linking DB error
[20240513 18:38:57 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:38:59 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:38:59 save_data.py:20 INFO]: Linking DB error
[20240513 18:39:02 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:39:04 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:39:04 save_data.py:20 INFO]: Linking DB error
[20240513 18:39:06 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:39:09 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:39:09 save_data.py:20 INFO]: Linking DB error
[20240513 18:39:11 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:39:13 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:39:13 save_data.py:20 INFO]: Linking DB error
[20240513 18:39:15 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:39:18 save_data.py:20 INFO]: [Error] Linking DB error; C:\Users\jimlee\AppData\Local\Programs\Python\Python310\lib\site-packages\psycopg2\__init__.py. connect at line 122.
[20240513 18:39:18 save_data.py:20 INFO]: Linking DB error
